workflows:
  android-build:
    name: Android APK
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_CHANNEL: stable
      node: 18
      ruby: 2.7
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
